AllCops:
  RunRailsCops: true
  Exclude:
    - 'db/schema.rb'
    - 'bin/**/*'
    - 'log/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'

Style/StringLiterals:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/LineLength:
  Max: 120
