# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4c11a74414cd51998c56d652a91ae9176d0387a7d8cc601deb02538a1cc5053c2d7b93d82d782b18539253e2d0f412508c8e55030559563f78743e34dfc96688

test:
  secret_key_base: 09e1b8e33f75e461c04697fe23d749439e6f493ee06d3d8e0eb738ff8e0cb5a7938c6f6908624000561630f5e5faf6600492c4eeaae3ac8e7e1db266f0e0ea2b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
